### ISSUE TITLE
Waku Relay not relaying

### ISSUE THREAD

**Issue by D4nte** [status-im/go-waku#22] opened 2021-04-29 05:00 UTC
Running go-waku 1c4555ab329f8f037fc45f2e2d5363f20685c11b on VPS `jdev`, connected to nim-waku test fleet (`...bUZ`).

```
./build/waku --nodekey <key>  --staticnodes /ip4/134.209.139.210/tcp/30303/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ --store --use-db --ws --relay
2021-04-29T03:47:14.643Z        INFO    wakurelay       Relay protocol started
2021-04-29T03:47:14.644Z        INFO    wakurelay       Subscribing to topic /waku/2/default-waku/proto
2021-04-29T03:47:14.644Z        INFO    wakunode        Subscribing store to topic /waku/2/default-waku/proto
2021-04-29T03:47:14.654Z        INFO    wakustore       Store protocol started
2021-04-29T03:47:14.655Z        INFO    wakunode        Listening on /ip4/128.199.61.231/tcp/9000/p2p/16Uiu2HAm7gwDpb2SQkWv69V7YND1v9tzs12eu1YyqNYmtEZwvC8D
2021-04-29T03:47:14.655Z        INFO    wakunode        Listening on /ip4/127.0.0.1/tcp/9000/p2p/16Uiu2HAm7gwDpb2SQkWv69V7YND1v9tzs12eu1YyqNYmtEZwvC8D
2021-04-29T03:47:14.656Z        INFO    wakunode        Listening on /ip4/128.199.61.231/tcp/9001/ws/p2p/16Uiu2HAm7gwDpb2SQkWv69V7YND1v9tzs12eu1YyqNYmtEZwvC8D
2021-04-29T03:47:14.656Z        INFO    wakunode        Listening on /ip4/127.0.0.1/tcp/9001/ws/p2p/16Uiu2HAm7gwDpb2SQkWv69V7YND1v9tzs12eu1YyqNYmtEZwvC8D
2021-04-29T03:47:14.660Z        INFO    swarm2  got error on dial: dial tcp4 0.0.0.0:30303: connect: connection refused
2021-04-29T03:47:24.631Z        INFO    basichost       DiscoverNAT error:no NAT found
2021-04-29T03:47:58.918Z        WARN    pubsub  error unmarshalling peer record obtained through px: failed when unmarshalling the envelope: asn1: syntax error: sequence truncated
```

Run "franck2" nim-waku chat2 7e9dac67c8927c953687ee6391c63286377bb9c9 node locally,connected to nim-waku test fleet (`...bUZ`):

```
/build/chat2 --storenode:/ip4/134.209.139.210/tcp/30303/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ --staticnode:/ip4/134.209.139.210/tcp/30303/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ
Choose a nickname >> franck2
Welcome, franck2!
Connecting to nodes
Listening on
 /ip4/0.0.0.0/tcp/60000/p2p/16Uiu2HAm2cPRGo1ukiWvvYYjZhWphxyduPiTBtceQYLj62nhQQES
<Apr 29, 13:30> cli: Hi!@
<Apr 29, 13:31> cli: Hi!!
<Apr 29, 13:38> nim-fr: hello there
>> yoooo
<Apr 29, 14:56> franck2: yoooo
```

Run "franck" nim-waku chat2 7e9dac67c8927c953687ee6391c63286377bb9c9 node locally, connected to remote go-waku instance:

```
▶ ./build/chat2 --staticnode:/ip4/64.225.83.205/tcp/9000/p2p/16Uiu2HAm7gwDpb2SQkWv69V7YND1v9tzs12eu1YyqNYmtEZwvC8D
Choose a nickname >> franck1
Welcome, franck1!
Connecting to nodes
Listening on
 /ip4/0.0.0.0/tcp/60000/p2p/16Uiu2HAm8vyBwweJ5g9S3VeoSbUFpwX85k52DtBZ115CPnyjKxQT
>> hello there
<Apr 29, 14:55> franck1: hello there
>> hiii
<Apr 29, 14:55> franck1: hiii
```

As you can see, messages are not being relayed through the test fleet.

There are also some error messages. not sure if it is related:
```
2021-04-29T03:47:14.660Z        INFO    swarm2  got error on dial: dial tcp4 0.0.0.0:30303: connect: connection refused
2021-04-29T03:47:24.631Z        INFO    basichost       DiscoverNAT error:no NAT found
2021-04-29T03:47:58.918Z        WARN    pubsub  error unmarshalling peer record obtained through px: failed when unmarshalling the envelope: asn1: syntax error: sequence truncated
```

**Comment by richard-ramos** [comment] 2021-04-29 13:38
For some reason I'm not able to connect to the fleet and I'm always getting this error:
```
2021-04-29T03:47:14.660Z        INFO    swarm2  got error on dial: dial tcp4 0.0.0.0:30303: connect: connection refused
```

I tried running locally both nim-waku and go-waku with the following configuration, and i'm able to get messages between both chat clients:
```
go-chat2 -> go-waku -> nim-waku <- nim-chat2
```

I'll try installing nim-waku on my DO droplet to see if I can connect to it from a local go-waku node.

**Comment by richard-ramos** [comment] 2021-04-29 14:26
I tried the following setup and I was able to get messages going back and forth between both nim and go. Perhaps there's some firewall rule or something that's causing the `connection refused` error?
```
go-chat2 (local) -> go-waku (remote, Droplet 1) -> nim-waku (remote, Droplet 2)  <- nim-chat2
```

cc: @jakubgs

**Comment by richard-ramos** [comment] 2021-04-29 14:27
I also noticed that the test fleet nodes are not relaying messages between themselves either.

**Comment by jm-clius** [comment] 2021-04-30 07:38
Yes, there seems to be some regression on the `test` cluster which I'll look into (`prod`, running a slightly older version, still seems to work).
The `test` fleet nodes not relaying between themselves is due to [this issue](https://github.com/status-im/nim-waku/issues/504) for which we hopefully have a workaround merged soon!

**Comment by jm-clius** [comment] 2021-04-30 12:51
I can relay messages via the cluster between nim clients again after updating the `chat2` client to the latest `nim-waku` master. The issue was a bump in the `WakuStoreCodec` version (to `"/vac/waku/store/2.0.0-beta3"`). Perhaps this is why you get the connection refused error?

**Comment by D4nte** [comment] 2021-05-03 04:03
FYI I opened an issue to track the relay problem with nim-waku: https://github.com/status-im/nim-waku/issues/527

**Comment by richard-ramos** [comment] 2021-07-21 22:37
This does not seem to be an issue anymore. I'm able to send messages using the test fleet. 
Feel free to reopen if the problem still persists

**Closed by richard-ramos** 2021-07-21 22:37 UTC
